<?php
return array (
  'EBAY-AT' => 'Austria',
  'EBAY-AU' => 'Australia',
  'EBAY-CH' => 'Switzerland',
  'EBAY-DE' => 'Germany',
  'EBAY-ENCA' => 'Canada (English)',
  'EBAY-ES' => 'Spain',
  'EBAY-FR' => 'France',
  'EBAY-FRBE' => 'Belgium (French)',
  'EBAY-FRCA' => 'Canada (French)',
  'EBAY-GB' => 'UK',
  'EBAY-HK' => 'Hong Kong',
  'EBAY-IE' => 'Ireland',
  'EBAY-IN' => 'India',
  'EBAY-IT' => 'Italy',
  'EBAY-MOTOR' => 'Motors',
  'EBAY-MY' => 'Malaysia',
  'EBAY-NL' => 'Netherlands',
  'EBAY-NLBE' => 'Belgium (Dutch)',
  'EBAY-PH' => 'Philippines',
  'EBAY-PL' => 'Poland',
  'EBAY-SE' => 'Sweden',
  'EBAY-SG' => 'Singapore',
  'EBAY-US' => 'United States',
);